// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ0bMqz3qgUVPV1Mf2J3sMVsShKvHzNZ0',
    appId: '1:187279847237:web:03e5beddd1f6eae27cd82c',
    messagingSenderId: '187279847237',
    projectId: 'uploader-c5f45',
    authDomain: 'uploader-c5f45.firebaseapp.com',
    storageBucket: 'uploader-c5f45.appspot.com',
    measurementId: 'G-2NEQHBB54X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGcpeqxRYiZf9NQh7gw9kQmAAsFicFa4',
    appId: '1:187279847237:android:6b46a2a981f3750c7cd82c',
    messagingSenderId: '187279847237',
    projectId: 'uploader-c5f45',
    storageBucket: 'uploader-c5f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqm-bh7zAk0IlWF1KnUaxfd0-OlwIXbo4',
    appId: '1:187279847237:ios:2ec526a79b96b48c7cd82c',
    messagingSenderId: '187279847237',
    projectId: 'uploader-c5f45',
    storageBucket: 'uploader-c5f45.appspot.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqm-bh7zAk0IlWF1KnUaxfd0-OlwIXbo4',
    appId: '1:187279847237:ios:6e4599d350fc5cdd7cd82c',
    messagingSenderId: '187279847237',
    projectId: 'uploader-c5f45',
    storageBucket: 'uploader-c5f45.appspot.com',
    iosBundleId: 'com.example.health.RunnerTests',
  );
}
